sudo: true
language: node_js 
node_js: 
    - 12 
cache: npm 
branches: 
    only: 
        - master # build master branch only 
script:
    - hexo clean
    - hexo generate 
deploy: 
    provider: pages 
    skip_cleanup: true 
    github-token: $GH_TOKEN 
    keep_history: true 
    on: 
        branch: master 
    local_dir: public
