name: HexoCI
on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source
              uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Setup
              env:
                  HEXO_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_SECRETS }}
              run: |
                mkdir -p ~/.ssh/
                echo "$HEXO_DEPLOY_KEY" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                ssh-keyscan github.com >> ~/.ssh/known_hosts
                git config --global user.email "huybery@gmail.com"
                git config --global user.name "huybery"
                sudo npm i -g hexo-cli
                npm i
                
            - name: hexo deploy
              run: |
                  hexo generate && hexo deploy
