name: HexoCI
on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source
              uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Setup
              run: |
                git config --global user.email "huybery@gmail.com"
                git config --global user.name "huybery"
                sudo npm i -g hexo-cli
                npm i
                
            - name: hexo deploy
              run: |
                  hexo g -d
