name: HexoCI
on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source
              uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Setup
              run: 
                npm install hexo-cli --g
                npm install
                hexo clean
                hexo generate
            - name: hexo deploy
              run:
                  hexo clean
                  hexo generate
                  hexo deploy
